# Copyright 2021 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  url:
    description: URL for the remote Alertmanager instance (including scheme and port number).
    type: string
